### ISSUE TITLE
Add a user info parameter to start AMI with out starting scylla services 

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-ami#1]
In many cases, Scylla AMI configuration need to be set **before** starting the services.
Adding a ```--start-service false``` option will help.

**Comment by syuu1228** [comment]
@avikivity Can we let systemd to cancel to boot up scylla-server.service in scylla-ami-setup.service script, by calling systemctl disable scylla-server?

**Comment by syuu1228** [comment]
Please check '[PATCH scylla] dist: abandon to start scylla-server when it's disabled from AMI userdata
' and '[PATCH scylla-ami] adding --stop-services'.
