### ISSUE TITLE
Allow Scylla AMI to run on a micro instance

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-ami#10]
Although not recommended for production, developers looking for functional evaluation will try to run Scylla on a free t2.micro instance
Currently Scylla AMI failed with a non clear error:
```
Jan 04 09:59:05 ip-172-30-0-66 audit[12432]: <audit-1701> auid=4294967295 uid=995 gid=1001 ses=4294967295 subj=system_u:system_r:unconfined_service_t:s0 pid=12432 comm="scylla" exe="/usr/bin/scylla" sig=6

```

**Comment by slivne** [comment]
I don't think we should chase this

We can limit the AMI to specific instance types (including some that are cheap).

If anyone want to use different instances he can always use the rpms

**Comment by tzach** [comment]
> I don't think we should chase this

Making scylla easy and cheap to test is enough of a motivation.
It will have a similar audience as Scylla on Docker: early adopters and developers, interested but lazy and does not like to pay (did I just described myself?)

**Comment by slivne** [comment]
Ok - so we can make a developer mode ami if we want to chase this - trying
to catch the "production ready" and the "run with the least resources
available" at the same time is not realistic - e.g we should at least set
--developer-mode for the "run with the least resources" - as currently we
require in addition to XFS ability to hold many file open that will eat up
a large part of memory (if I'm not mistaken).

**Comment by dorlaor** [comment]
It's a good idea to run there with --developer-mode.
Indeed it's not recommended for production but is very helpful for
developers and first time use. Users don't really read the docs so
it should be good to run there.

**Comment by tzach** [comment]
developer-mode is a good idea.
Adding a developer-mode warning on the SSH prompt is a nice complementary

**Comment by slivne** [comment]
I think it should be two different AMIs to make it clear
- we can even make them "opposite" to each other
- the production should only run on the instances we "certified" i2 / c3.
the developer can only run on all the rest (and not run on i2, c3)

The prompt on login can be added.

**Comment by tzach** [comment]
> I think it should be two different AMIs to make it clear

+1

**Comment by syuu1228** [comment]
I able to run recent AMI on t2.micro so I don't understand what should we fix.

About to having two different AMIs, maybe we should add an additional argument on dist/ami/build_ami.sh to specify which one do we want to build, use different IAM policies, and specify --developer-mode on developer AMI?

**Comment by slivne** [comment]
Closing this - till we have a new issue with the micro and then decide what
we do with it - if it currently works thats good enough for now

**Comment by slivne** [comment]
Avi fixed this
