### ISSUE TITLE
scylla ami use XFS as the root file system 

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-ami#11]
starting from 0.14 Scylla mandates XFS (unless --developer-mode true) is set.

current AMI does not use XFS for the root volume as such a user must attach additional drives to use Scylla AMI.

Make the root device using XFS so that we can run without attaching additional drives.

**Comment by avikivity** [comment]
Maybe switching to a centos AMI will fix that, since xfs is the default filesystem in centos.

**Comment by syuu1228** [comment]
On this AMI, we will not support RAID anymore, right?
I don't think we can create RAID with root disk + one more extra disk, what else can we do?

**Comment by slivne** [comment]
- On this AMI, we will not support RAID anymore, right?

Why not

- We want the root disk to be XFS so that a user that does not attach
additional drives will be able to use scylla (without the --developer-mode)

- If the user does attach disks we will create a raid over the additional
disks he provides and that will be used for the data/commitlog etc.

**Comment by syuu1228** [comment]
Okay, so use RAID only when $NR_DISKS >= 2.

**Comment by slivne** [comment]
The root file system should be used for data if there are no additional
disks

If there are additional disks they should be used for data.

If there is a X=1 additional disk lets format it without raid

If there are X > 1 additional disks lets create a RAID 0 over them

**Comment by syuu1228** [comment]
This was fixed.
