### ISSUE TITLE
Mark the root disk with delete_on_termination  

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-ami#14]
Our ami root disk does not have the delete_on_termination flag set oin the storage tab.

This forces to update the setting / remove left over volumes - lets update the ami to have this preset by defaullt.

ubuntu ami has this preset

**Comment by syuu1228** [comment]
Please check '[PATCH scylla] dist: On AMI, mark root disk with delete_on_termination'

**Comment by penberg** [comment]
Fixed by https://github.com/scylladb/scylla/commit/f227b3faacfba185c8dc976bd28650123a652940
