### ISSUE TITLE
scylla 1.3.1 AMI doesn't have a collectd_exporter in it

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla-ami#19]
Just like the subject said. I had to install it manually. Not sure if that's the best user experience.

**Comment by vladzcloudius** [comment]
`/etc/collectd.d/scylla.conf` file is missing all `prometeus` related configuration.

**Comment by slivne** [comment]
collectd_exporter is not part of ani AMI starting from 1.4 we support
prometheus and install the node_exporter
