### ISSUE TITLE
Create a tmp file as a sign of complete init

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-ami#2]
When working with external config tool, like Ansible, its important to know when the AMI init process is done, to avoid updating the same files, packages.
One way to do it is for the AMI init scripts to create a /tmp/ami_done file.
This file can be use as a semaphore to Ansible [wait_for](http://docs.ansible.com/ansible/wait_for_module.html)

**Comment by syuu1228** [comment]
We can use /etc/scylla/ami_configured on latest AMI

**Comment by syuu1228** [comment]
Please close this.
