### ISSUE TITLE
Enable EBS based AMI

### ISSUE THREAD

**Issue by eyalgutkind** [scylladb/scylla-ami#20]
Using Scylla 1.6 AMI, ami-930bb0f3
Instances used C3.2xlarge.

Attaching an EBS volume to the AMI volume along with SSD based volume makes the following:
1. The EBS volume is not recognized by the AMI script, and do not join the raid volume, in the case below the EBS volume of 3.4TB is not joining the RAID volume (/dev/xvdf)

[centos@ip-172-31-27-168 ~]$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda1       10G  3.0G  7.1G  30% /
devtmpfs        7.3G     0  7.3G   0% /dev
tmpfs           7.2G     0  7.2G   0% /dev/shm
tmpfs           7.2G  8.3M  7.2G   1% /run
tmpfs           7.2G     0  7.2G   0% /sys/fs/cgroup
/dev/md0        160G  195M  160G   1% /var/lib/scylla
tmpfs           1.5G     0  1.5G   0% /run/user/1000
[centos@ip-172-31-27-168 ~]$ sudo fdisk -l

Disk /dev/xvda: 10.7 GB, 10737418240 bytes, 20971520 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk label type: dos
Disk identifier: 0x00010209

    Device Boot      Start         End      Blocks   Id  System
/dev/xvda1   *        2048    20971519    10484736   83  Linux

Disk /dev/xvdb: 85.9 GB, 85887811584 bytes, 167749632 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/xvdc: 85.9 GB, 85887811584 bytes, 167749632 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes

Disk /dev/xvdf: 3650.7 GB, 3650722201600 bytes, 7130316800 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

Disk /dev/md0: 171.6 GB, 171641405440 bytes, 335237120 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 1048576 bytes / 2097152 bytes

[centos@ip-172-31-27-168 ~]$ cat /proc/mdstat
Personalities : [raid0]
md0 : active raid0 xvdc[1] xvdb[0]
      167618560 blocks super 1.2 1024k chunks

2. In such a case, allow the user for example to use the SSD RAID volume to the commitlog and the EBS volume as the data volume.

It seems like a common scenario, in cases using EBS.

**Comment by glommer** [comment]
Eyal, what do you mean by:

"The EBS volume is not recognized by the AMI script, and do not join the raid volume" ?

I had the exact opposite experience. The EBS *do* join the raid, which is a big, big problem. EBS and local SSDs for AWS have different lifetimes. If you just reboot the machine, the data in the SSD volumes will disappear, corrupting the raid.

We need to script to recognize (with the help of userdata if necessary) EBS versus SSD volumes and create separate RAIDs for them. Then based on that, mount them to different locations.
