### ISSUE TITLE
Failed to copy AMI

### ISSUE THREAD

**Issue by devwout** [scylladb/scylla-ami#38]
It does not seem to be possible to copy `ami-3ceac343`. AWS returned the following error:

```
InvalidRequest: You do not have permission to access the storage of this ami
```

Is this intentional? When running an AMI in production it is desired to copy the AMI to protect against it (perhaps unintentionally) disappearing. Copying an AMI is also required for EBS root encryption.

**Comment by tzach** [comment]
Its is not intentional
@penberg any idea how to change that?

**Comment by tzach** [comment]
Atlgho the AMI is public, the snapshot of the root volume is private

**Comment by devwout** [comment]
Any way the snapshot can be made public as well?

**Comment by tzach** [comment]
@syuu1228 ?

**Comment by syuu1228** [comment]
I actually cannot reproduce the issue, I able to copy ami-3ceac343 to ami-06a848a0e9177ba2f.

**Comment by tzach** [comment]
@syuu1228 I suspect this is because you are using Scylla account.
Other accounts will fail to do so, even though the AMI is public.

**Comment by devwout** [comment]
Tried again, not possible to copy the AMI using our account. The AMI is public, but the EBS snapshot for the AMI is not public.

The snapshot for `ami-3ceac343` is `snap-02c838a592ee518d9`.

According to [the docs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-modifying-snapshot-permissions.html), you can lookup this snapshot in the EC2 console, go to Actions > Modify Permissions and make it public.

**Comment by syuu1228** [comment]
@devwout @tzach Okay confirmed the issue and changed snapshot permission. Now I able to copy ami-3ceac343 with my private AWS account.

**Comment by devwout** [comment]
Works for me too, thank you for fixing this!
