### ISSUE TITLE
Cluster name not correctly set

### ISSUE THREAD

**Issue by devwout** [scylladb/scylla-ami#40]
Using ami-3ceac343 .

Set the cluster name in user data with `--clustername mycluster`.

```
$ nodetool describecluster
Cluster Information:
        Name: Test Cluster
```

```
$ cat /etc/scylla/scylla.yaml | grep cluster_name
#cluster_name: 'xxx'
```

In [ds2_configure.py](https://github.com/scylladb/scylla-ami/blob/master/ds2_configure.py#L434), the cluster name is replaced in the yaml file. However, this line is commented and it remains commented after replacing the cluster name.

**Comment by tzach** [comment]
Duplicate with #35
