### ISSUE TITLE
After the 2.2 AMI gets updated to 2.3, scripts run upon login fail

### ISSUE THREAD

**Issue by dyasny** [scylladb/scylla-ami#41]
When using ScyllaDB 2.2.0 (ami-3ceac343), as I login via SSH I get the `nodetool status` and a general status of whether Scylla is running.

If I change the yum repo to 2.3 and `yum update` scylla to the latest, this login information becomes broken:

```sh
 $ ssh centos@184.72.81.49
Last login: Tue Aug  7 14:54:16 2018 from 141.226.123.200
-bash: /usr/lib/scylla/scylla_lib.sh: No such file or directory

   _____            _ _       _____  ____  
  / ____|          | | |     |  __ \|  _ \ 
 | (___   ___ _   _| | | __ _| |  | | |_) |
  \___ \ / __| | | | | |/ _` | |  | |  _ < 
  ____) | (__| |_| | | | (_| | |__| | |_) |
 |_____/ \___|\__, |_|_|\__,_|_____/|____/ 
               __/ |                       
              |___/                        


Nodetool:
	nodetool help
CQL Shell:
	cqlsh
More documentation available at: 
	http://www.scylladb.com/doc/
By default, Scylla sends certain information about this node to a data collection server. For information, see http://www.scylladb.com/privacy/

-bash: is_systemd: command not found
-bash: is_systemd: command not found
-bash: initctl: command not found
-bash: ec2_is_supported_instance_type: command not found
-bash: [: -eq: unary operator expected
    ScyllaDB is not started!
Please wait for startup. To see status of ScyllaDB, run 
-bash: is_systemd: command not found
 'initctl status scylla-server'
and
 'sudo cat /var/log/upstart/scylla-server.log'
```

Hovewer, the scylla-server service is running and I am using the database with no issues:
```sh
[centos@ip-172-30-0-216 ~]$ sudo systemctl status scylla-server
● scylla-server.service - Scylla Server
   Loaded: loaded (/usr/lib/systemd/system/scylla-server.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/scylla-server.service.d
           └─capabilities.conf
   Active: active (running) since Tue 2018-08-07 14:37:25 UTC; 17min ago
  Process: 5766 ExecStopPost=/usr/lib/scylla/scylla_stop (code=exited, status=0/SUCCESS)
  Process: 5804 ExecStartPre=/usr/lib/scylla/scylla_prepare (code=exited, status=0/SUCCESS)
 Main PID: 5829 (scylla)
   Status: "serving"
   CGroup: /system.slice/scylla-server.service
           └─5829 /usr/bin/scylla --log-to-syslog 1 ...

Aug 07 14:45:22 ip-172-30-0-216.ec2.internal scylla[5829]: ...
Aug 07 14:45:23 ip-172-30-0-216.ec2.internal scylla[5829]: ...
Aug 07 14:45:24 ip-172-30-0-216.ec2.internal scylla[5829]: ...
Aug 07 14:45:24 ip-172-30-0-216.ec2.internal scylla[5829]: ...
Aug 07 14:45:32 ip-172-30-0-216.ec2.internal scylla[5829]: ...
Aug 07 14:45:32 ip-172-30-0-216.ec2.internal scylla[5829]: ...
Aug 07 14:45:32 ip-172-30-0-216.ec2.internal scylla[5829]: ...
Aug 07 14:45:32 ip-172-30-0-216.ec2.internal scylla[5829]: ...
Aug 07 14:45:49 ip-172-30-0-216.ec2.internal scylla[5829]: ...
Aug 07 14:45:49 ip-172-30-0-216.ec2.internal scylla[5829]: ...
Hint: Some lines were ellipsized, use -l to show in full.


[centos@ip-172-30-0-146 ~]$ nodetool status
Datacenter: us-east
===================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load       Tokens       Owns    Host ID                               Rack
UN  172.30.0.216  26.77 GB   256          ?       b2aed817-5db4-48c5-a5af-6894e9db5061  1b
UN  172.30.0.132  26.92 GB   256          ?       90fd497a-cc5e-4f5e-8317-ca4fbacd44cd  1b
UN  172.30.0.146  26.75 GB   256          ?       cd585152-c3b0-44e2-9ac6-ebd2accd6c84  1b

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
```

Versions:
[centos@ip-172-30-0-146 ~]$ rpm -qa |grep scylla
scylla-tools-core-2.3.rc1-20180726.058564c10.el7.noarch
scylla-tools-2.3.rc1-20180726.058564c10.el7.noarch
scylla-kernel-conf-2.3.rc1-0.20180726.adad12ddc.el7.x86_64
scylla-env-1.1-1.el7.noarch
scylla-libstdc++73-7.3.1-1.2.el7.centos.x86_64
scylla-jmx-2.3.rc1-20180726.1dc4338.el7.noarch
scylla-libgcc73-7.3.1-1.2.el7.centos.x86_64
scylla-server-2.3.rc1-0.20180726.adad12ddc.el7.x86_64
scylla-debuginfo-2.3.rc1-0.20180726.adad12ddc.el7.x86_64
scylla-conf-2.3.rc1-0.20180726.adad12ddc.el7.x86_64
scylla-2.3.rc1-0.20180726.adad12ddc.el7.x86_64

**Comment by tzach** [comment]
@amoskong FYI you should see this in the upgrade tests

**Comment by syuu1228** [comment]
This is not just a bug, currently we don't have way to upgrade AMI related files such as /home/centos/.bash_profile (login prompt) and /usr/lib/scylla/scylla-ami (AMI initialization script that automatically configures scylla.yaml by userdata, and construct RAID volume), since these files are not managed by .rpm.
The error comes from changes from v2.2 to v2.3 so we updated dist/ami/files/.bash_profile and dist/ami/files/scylla-ami to support it, but changes only apply to newly created 2.3 AMI, not for existing 2.2 AMI instances.

Probably we can provide new AMI files by some .rpm packaging hack -
Archive new AMI files into .tar file, upload the file to our S3.
Then %post (or %posttrans) if package upgrade is executed on Scylla AMI-2.2 or older (detect by /usr/lib/scylla/scylla-ami), download .tar file and extract it.

On future releases we probably should provide everything by .rpm package, including enhanced networking kernel modules (ENA and ixgbevf).

**Comment by syuu1228** [comment]
@avikivity What do you think, should we provide AMI script upgrade by rpm hack that I described? https://github.com/scylladb/scylla-ami/issues/41#issuecomment-411269137

**Comment by syuu1228** [comment]
Sent RFC patch for this, please review: "[RFC scylla] dist/redhat: provide AMI script update via 2.3 package"

**Comment by slivne** [comment]
starting from 3.0 we have a scylla-ami rpm that should make this upgrades possible - still needs verification

@roydahan - lets queue this and close

**Comment by tzach** [comment]
Closing.
@slivne @roydahan not sure what you want to queue

**Comment by roydahan** [comment]
we added a task to test upgrades from AMI.
Currently all upgrade tests are in GCE.
