### ISSUE TITLE
auto_bootstrap settings in the AMI are unsafe and can lead to data loss if user is not careful

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla-ami#46]
Our AMI defaults to auto_bootstrap: false.

This is incredibly unsafe, because a user who isn't paying attention may add a node to the cluster and not transfer any ranges to that node.

However this is made much worse by our docs: our docs claim left and right that the default value of auto_bootstrap is true (because that is indeed the case for the scylla binary, except that the AMI explicitly flips it)

If that was not enough, neither in the add page, nor in the EC2 page, do we say that the default can be false if the user is on the AMI.

It is my impression that this can be flipped through user-data, but once again, we don't seem to document it in the proper places (it's not in the EC2 page, and it is not in the add node page)

I believe we should strongly reconsider shipping such an unsafe default, and more than that, since by now they are plenty AMIs around with it, patch our docs strongly recommending users not to rely on the default for that flag and set it explicitly according to what they want to do.

**Comment by glommer** [comment]
@slivne @avikivity @tzach

**Comment by tzach** [comment]
Agree about not documenting this issue properly.
This part of the code was inherited, not sure what was the original motivation for it

Reasons for using auto_bootstrap as false might be:
- easier to launch a new cluster, for example with the reflector (?)
- one might need to take extra steps before the node become active.
(in this case, the user-data can be used)

**Comment by glommer** [comment]
If we inherit it, I propose we just change it and make our lives easier and safer.

We can look at those things like new cluster and test them, of course, to make sure there isn't any ill-behavior from it (I can't see why), but ultimately I believe it is a horrible default.

Documentation should happen anyway because of old AMIs

**Comment by glommer** [comment]
@dyasny please add your measurements here

**Comment by glommer** [comment]
@tzach reminder, as per discussion in the context of docs, we have agreement to change this parameter to a safer default.

@dyasny measured that the boot time of empty cluster is not really that much affected by that option.

**Comment by dorlaor** [comment]
@slivne pls do it ASAP

**Comment by slivne** [comment]
patch on the mailing list "[PATCH scylla-ami] Change the default of auto_bootstrap to be True"
