### ISSUE TITLE
Add AMI for *ALL* regions

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-ami#48]
We are getting more and more requests for AMI in different regions
Best will be to add AMI in all regions.

**Comment by tzach** [comment]
#45

**Comment by tzach** [comment]
@hagitsegev can we close this (for open source)?

**Comment by hagitsegev** [comment]
Can close. I have an [issue on pkg](https://github.com/scylladb/scylla-pkg/issues/333) (needs review).
To which releases do you want it? Old releases too?

**Comment by tzach** [comment]
Future releases only.
