### ISSUE TITLE
RPM build error "This macro requires some arguments" occurs on Fedora 31

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla-ami#53]
It seems like rpm macro %systemd_postun requires one argument starting from Fedora 31, otherwise it causes the error.
The solution is passing systemd unit name just like %systemd_post and  %systemd_preun.
see: https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/TU3T2ZYY67SMAJFR2TD4HY6SCPPDVS5V/

**Comment by hagitsegev** [comment]
I also just faced it on https://jenkins.scylladb.com/job/scylla-master/job/debug-jobs/job/centos-rpm-debug/53/consoleFull Ran on muninn

**Comment by hagitsegev** [comment]
I see that https://jenkins.scylladb.com/job/scylla-master/job/centos-rpm/5/consoleFull was OK on munnin 18 hours ago, but now fails on muninn.
And that https://jenkins.scylladb.com/job/scylla-master/job/debug-jobs/job/centos-rpm-debug/51/ was OK on thor yesterday, and now fails on Thor.

**Comment by hagitsegev** [comment]
@syuu1228 I tried to build centos-rpm using dbuild, and get syntax error:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/debug-jobs/job/centos-rpm-debug/56/console
```
14:04:05  find: 'debug': No such file or directory
14:04:05  + /usr/lib/rpm/check-buildroot
14:04:05  + /usr/lib/rpm/redhat/brp-ldconfig
14:04:05  + /usr/lib/rpm/brp-compress
14:04:05  + /usr/lib/rpm/brp-strip-static-archive /usr/bin/strip
14:04:06  + /usr/lib/rpm/redhat/brp-python-bytecompile /usr/bin/python 1 0
14:04:06  Bytecompiling .py files below /jenkins/slave/workspace/scylla-master/debug-jobs/centos-rpm-debug/scylla-tools-java/build/redhat/BUILDROOT/scylla-tools-666.development-20191208.35906df2a0d.x86_64/usr/lib/python3.7 using /usr/bin/python3.7
14:04:06  *** Error compiling '/jenkins/slave/workspace/scylla-master/debug-jobs/centos-rpm-debug/scylla-tools-java/build/redhat/BUILDROOT/scylla-tools-666.development-20191208.35906df2a0d.x86_64/usr/lib/python3.7/site-packages/cqlshlib/copyutil.py'...
14:04:06    File "/usr/lib/python3.7/copyutil.py", line 141
14:04:06      except Exception, e:
```
and more errors.

**Comment by avikivity** [comment]
If it's a new problem, open a new issue, don't reopen an unrelated issue.
