### ISSUE TITLE
AMI deafult snitch should be EC2Snitch, not simple snitch

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-ami#6]
Running on EC2, AMI should use the EC2Snitch

**Comment by tzach** [comment]
* @slivne @vladzcloudius @syuu1228  what do you think?
* Should I move this bug on the main project?

**Comment by tzach** [comment]
Cassandra AMI use EC2Snitch

**Comment by slivne** [comment]
I'll ask taluya to handle it - it should be simple. you can leave it at its
current position.

**Comment by tzach** [comment]
ping

**Comment by syuu1228** [comment]
I tested to modify scylla.yaml to use EC2Snitch for endpoint_snitch, but I got
'Exiting on unhandled exception of type 'no_such_class': unable to find class 'EC2Snitch''
Also tested with org.apache.cassandra.locator.EC2Snitch, same result.

**Comment by tzach** [comment]
Maybe we do not have EC2Snitch, is so its a Scylla bug

**Comment by slivne** [comment]
We di have it and also multi region version @vlad-cloudius

**Comment by vladzcloudius** [comment]
On 01/21/2016 11:39 AM, Takuya ASADA wrote:
>
> I tested to modify scylla.yaml to use EC2Snitch for endpoint_snitch, 
> but I got
> 'Exiting on unhandled exception of type 'no_such_class': unable to 
> find class 'EC2Snitch''
> Also tested with org.apache.cassandra.locator.EC2Snitch, same result.
>

that's because it's name is Ec2Snitch ;)

**Comment by syuu1228** [comment]
Ah okay, will try again :-)

**Comment by syuu1228** [comment]
I was looking on this,
https://github.com/scylladb/scylla/blob/master/locator/ec2_snitch.hh#L35
Maybe this should be renamed to Ec2Snitch too?
