### ISSUE TITLE
Add support for launching an AMI instance and connecting it to an existing cluster

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-ami#7]
Add support for 

```
--clustername $cluster_name_want_to join
--seed_ip $existing_seed_node 
```

so that the node will launch and attach itself to the cluster using the seed_ips

**Comment by syuu1228** [comment]
Is this different with existing '--seeds' option?

**Comment by slivne** [comment]
I did not find the --seeds :( - thanks  :)

if it allows the exact same things - great - can you just validate that we
can add a node using the --seeds option to an existing cluster and if so
close this.

**Comment by syuu1228** [comment]
--seeds tested, it able to assign both single node and multiple nodes. so please close this.
