### ISSUE TITLE
cqlsh does not connect to scylla IP by default

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-ami#8]
When launching Cassandra AMI, `cqlsh` without any parameter works.
With Scylla AMI (0.13.2), only `cqlsh internal-ip` works

**Comment by penberg** [comment]
We could override the default configuration by adding this in the ``~/.cassandra/cqlshrc`` file:

```
[connection]
hostname = <internal-ip>
```

**Comment by syuu1228** [comment]
I'm not sure why but it doesn't happen on latest build.

**Comment by syuu1228** [comment]
Please close this.
