### ISSUE TITLE
Create AMI with attached SSD

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-ami#9]
Scylla require attached drives in addition to ephemeral one.
It is possible to create an AMI in a way which will include such drives by default.

"Creates an Amazon EBS-backed AMI from an Amazon EBS-backed instance that is either running or stopped.

If you customized your instance with instance store volumes or Amazon EBS volumes in addition to the root device volume, the new AMI contains block device mapping information for those volumes. When you launch an instance from this new AMI, the instance automatically launches with those additional volumes."
http://docs.aws.amazon.com/AWSEC2/latest/CommandLineReference/ApiReference-cmd-CreateImage.html

**Comment by slivne** [comment]
Todo this it seems we need to update the pakcer and force it to use  https://packer.io/docs/builders/amazon-ebs.html#ami_block_device_mappings

there is a sample also on the page for our specific case 

It is not clear to me how this will work in case there is only a single device to attach for the instance type / there are more devices to attach for the instance type - if its possible lets attach the maximum (e.g. I think its 6 devices for the high end i2)

**Comment by syuu1228** [comment]
Isn't it conflicting this issue? https://github.com/scylladb/scylla-ami/issues/11
After we closed #11, we don't need extra disks by default.

**Comment by slivne** [comment]
No its not conflicting ....

It means that the root file system which is EBS will be using XFS and a
user can decide to run only with that  / run on instances that do not have
attached disks.

If the user runs on machines with attached disks - they should default to
ephemeral and attach as many as possible.

**Comment by syuu1228** [comment]
We can force to use additional ephemeral disk(s) by default, is that what we want?
Maybe add two, and construct RAID by default?

**Comment by slivne** [comment]
I think we should force to use the maximum ephemeral that exist (e.g. in
i2.4x,i2.8x there are more then 2).

as an example ubuntu ami on i2.8x sets it up with 8 disks, on i2.4x you get
4 ... etc.

**Comment by syuu1228** [comment]
I think it requires

2016年2月2日火曜日、slivne<notifications@github.com>さんは書きました:

**Comment by syuu1228** [comment]
I think it requires multiple AMIs whitch have different numbers of
ephemeral disks, no?

2016年2月2日火曜日、Takuya ASADA<syuu@scylladb.com>さんは書きました:

**Comment by slivne** [comment]
No for ubuntu its the same AMI as far as I can tell - use AWS console start
an Ubuntu 14.04 from the console on i2.8x and see the ami id start it on a
i2.xlarge and check the ami id - I think its the same

It could be that the AMI knows to allow usage of epeheral only if they
exist - try it out

**Comment by syuu1228** [comment]
Please check '[PATCH scylla v2] dist: attach ephemeral disks on AMI by default'.

**Comment by syuu1228** [comment]
This was merged at https://github.com/scylladb/scylla/commit/09b1ec6103c644407f682de1097a1ebc94739447, so please close it.
